import { Loja, Produto, Encomenda, Carrinha } from '../types';

export const LOJAS_MOCK: Loja[] = [
  {
    id: 'loja-1',
    codigo: 'LOJA-1',
    nome: 'Padaria & Pastelaria Central (Matriz)',
    morada: 'Av. Principal 100, Lisboa',
    telefone: '210 000 001',
    nif: '500100201',
    ativo: true,
  },
  {
    id: 'loja-2',
    codigo: 'LOJA-2',
    nome: 'Padaria & Pastelaria Baixa',
    morada: 'Rua Augusta 45, Lisboa',
    telefone: '210 000 002',
    nif: '500100202',
    ativo: true,
  },
  {
    id: 'loja-3',
    codigo: 'LOJA-3',
    nome: 'Padaria & Pastelaria do Parque',
    morada: 'Alameda das Flores 12, Lisboa',
    telefone: '210 000 003',
    nif: '500100203',
    ativo: true,
  },
  {
    id: 'loja-4',
    codigo: 'LOJA-4',
    nome: 'Padaria & Pastelaria Estação',
    morada: 'Praça da Estação 8, Lisboa',
    telefone: '210 000 004',
    nif: '500100204',
    ativo: true,
  },
];

export const CARRINHAS_MOCK: Carrinha[] = [
  { id: 'car-1', loja_id: 'loja-1', identificador: 'Carrinha 1 - Matriz', matricula: '42-AB-89', ativo: true },
  { id: 'car-2', loja_id: 'loja-2', identificador: 'Carrinha 2 - Baixa', matricula: '77-ZX-12', ativo: true },
  { id: 'car-3', loja_id: 'loja-3', identificador: 'Carrinha 3 - Parque', matricula: '15-TR-33', ativo: true },
  { id: 'car-4', loja_id: 'loja-4', identificador: 'Carrinha 4 - Estação', matricula: '90-KL-55', ativo: true },
];

export const PRODUTOS_MOCK: Produto[] = [
  // Padaria
  { id: 'prod-1', nome: 'Pão Alentejano Tradicional', categoria: 'padaria', preco: 1.60, unidade: 'unidade', ativo: true },
  { id: 'prod-2', nome: 'Pão de Mafra', categoria: 'padaria', preco: 1.40, unidade: 'unidade', ativo: true },
  { id: 'prod-3', nome: 'Broa de Milho Tradicional', categoria: 'padaria', preco: 2.20, unidade: 'unidade', ativo: true },
  { id: 'prod-4', nome: 'Baguete Rústica de Cereais', categoria: 'padaria', preco: 1.10, unidade: 'unidade', ativo: true },
  { id: 'prod-5', nome: 'Pão de Forma Artesanal', categoria: 'padaria', preco: 2.80, unidade: 'unidade', ativo: true },
  { id: 'prod-6', nome: 'Regueifa Doce com Canela', categoria: 'padaria', preco: 7.50, unidade: 'unidade', ativo: true },

  // Pastelaria
  { id: 'prod-7', nome: 'Pastel de Nata (Caixa 6 un)', categoria: 'pastelaria', preco: 6.90, unidade: 'unidade', ativo: true },
  { id: 'prod-8', nome: 'Bolo de Aniversário Personalizado', categoria: 'pastelaria', preco: 18.50, unidade: 'kg', ativo: true },
  { id: 'prod-9', nome: 'Croissant Francês Manteiga', categoria: 'pastelaria', preco: 1.35, unidade: 'unidade', ativo: true },
  { id: 'prod-10', nome: 'Bola de Berlim com Creme de Ovos', categoria: 'pastelaria', preco: 1.50, unidade: 'unidade', ativo: true },
  { id: 'prod-11', nome: 'Mil-Folhas Crocante com Ovos Moles', categoria: 'pastelaria', preco: 1.70, unidade: 'unidade', ativo: true },
  { id: 'prod-12', nome: 'Tarte de Fruta Fresca', categoria: 'pastelaria', preco: 16.00, unidade: 'unidade', ativo: true },

  // Outros
  { id: 'prod-13', nome: 'Sumo de Laranja Natural 500ml', categoria: 'bebidas_outros', preco: 2.90, unidade: 'unidade', ativo: true },
];

export const ENCOMENDAS_INICIAIS: Encomenda[] = [
  {
    id: 'enc-101',
    numero_sequencial: 101,
    codigo: 'ENC-L1-0101',
    loja_id: 'loja-1',
    loja_nome: 'Padaria & Pastelaria Central (Matriz)',
    cliente: {
      id: 'cli-1',
      nome: 'Maria Fernandes',
      telefone: '912 345 678',
      morada: 'Rua das Flores 14, 2º Esq, Lisboa',
      codigo_postal: '1200-195',
      notas_entrega: 'Tocar no 2º Esq. Campainha do lado direito.',
    },
    tipo: 'entrega_domicilio',
    carrinha_id: 'car-1',
    carrinha_nome: 'Carrinha 1 - Matriz',
    data_agendamento: '2026-09-13',
    hora_agendamento: '09:30',
    estado: 'em_producao',
    estado_pagamento: 'pago',
    metodo_pagamento: 'mbway',
    total: 39.40,
    notas_cliente: 'Entregar antes das 10h impreterivelmente.',
    itens: [
      {
        id: 'item-1',
        encomenda_id: 'enc-101',
        produto_id: 'prod-8',
        produto_nome: 'Bolo de Aniversário Personalizado',
        setor: 'pastelaria',
        quantidade: 1.5,
        preco_unitario: 18.50,
        notas_personalizacao: 'Massa pão de ló, recheio ovos moles. Frase: Parabéns Afonso!',
        estado_producao: 'em_preparo',
      },
      {
        id: 'item-2',
        encomenda_id: 'enc-101',
        produto_id: 'prod-1',
        produto_nome: 'Pão Alentejano Tradicional',
        setor: 'padaria',
        quantidade: 2,
        preco_unitario: 1.60,
        notas_personalizacao: 'Bem cozido.',
        estado_producao: 'pronto',
      },
      {
        id: 'item-3',
        encomenda_id: 'enc-101',
        produto_id: 'prod-7',
        produto_nome: 'Pastel de Nata (Caixa 6 un)',
        setor: 'pastelaria',
        quantidade: 1,
        preco_unitario: 6.90,
        estado_producao: 'pronto',
      },
    ],
    criado_em: '2026-09-12T08:30:00Z',
  },
  {
    id: 'enc-102',
    numero_sequencial: 102,
    codigo: 'ENC-L1-0102',
    loja_id: 'loja-1',
    loja_nome: 'Padaria & Pastelaria Central (Matriz)',
    cliente: {
      id: 'cli-2',
      nome: 'António Silva',
      telefone: '967 890 123',
    },
    tipo: 'levantamento_loja',
    data_agendamento: '2026-09-13',
    hora_agendamento: '11:00',
    estado: 'pendente',
    estado_pagamento: 'pendente',
    metodo_pagamento: 'multibanco',
    total: 14.80,
    notas_cliente: 'Vem buscar ao balcão às 11h.',
    itens: [
      {
        id: 'item-4',
        encomenda_id: 'enc-102',
        produto_id: 'prod-2',
        produto_nome: 'Pão de Mafra',
        setor: 'padaria',
        quantidade: 4,
        preco_unitario: 1.40,
        estado_producao: 'pendente',
      },
      {
        id: 'item-5',
        encomenda_id: 'enc-102',
        produto_id: 'prod-9',
        produto_nome: 'Croissant Francês Manteiga',
        setor: 'pastelaria',
        quantidade: 4,
        preco_unitario: 1.35,
        estado_producao: 'pendente',
      },
      {
        id: 'item-6',
        encomenda_id: 'enc-102',
        produto_id: 'prod-3',
        produto_nome: 'Broa de Milho Tradicional',
        setor: 'padaria',
        quantidade: 1,
        preco_unitario: 2.20,
        estado_producao: 'pendente',
      },
    ],
    criado_em: '2026-09-12T10:15:00Z',
  },
  {
    id: 'enc-103',
    numero_sequencial: 103,
    codigo: 'ENC-L2-0103',
    loja_id: 'loja-2',
    loja_nome: 'Padaria & Pastelaria Baixa',
    cliente: {
      id: 'cli-3',
      nome: 'Café & Restaurante O Tejo',
      telefone: '218 765 432',
      morada: 'Rua dos Fanqueiros 88, Lisboa',
      codigo_postal: '1100-231',
      notas_entrega: 'Entrada das traseiras para fornecedores.',
    },
    tipo: 'entrega_domicilio',
    carrinha_id: 'car-2',
    carrinha_nome: 'Carrinha 2 - Baixa',
    data_agendamento: '2026-09-13',
    hora_agendamento: '07:30',
    estado: 'pronto_loja',
    estado_pagamento: 'pendente',
    metodo_pagamento: 'transferencia',
    total: 54.00,
    notas_cliente: 'Fornecimento matinal diário.',
    itens: [
      {
        id: 'item-7',
        encomenda_id: 'enc-103',
        produto_id: 'prod-4',
        produto_nome: 'Baguete Rústica de Cereais',
        setor: 'padaria',
        quantidade: 30,
        preco_unitario: 1.10,
        estado_producao: 'pronto',
      },
      {
        id: 'item-8',
        encomenda_id: 'enc-103',
        produto_id: 'prod-7',
        produto_nome: 'Pastel de Nata (Caixa 6 un)',
        setor: 'pastelaria',
        quantidade: 3,
        preco_unitario: 6.90,
        estado_producao: 'pronto',
      },
    ],
    criado_em: '2026-09-12T11:00:00Z',
  },
];
