//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  import type { TinaMarkdownContent } from 'tinacms/dist/rich-text';
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
  /** A rich-text document, renderable by TinaMarkdown */
  RichText: { input: TinaMarkdownContent; output: TinaMarkdownContent; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  configuracao: Configuracao;
  configuracaoConnection: ConfiguracaoConnection;
  lojas: Lojas;
  lojasConnection: LojasConnection;
  produtos: Produtos;
  produtosConnection: ProdutosConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryConfiguracaoArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryConfiguracaoConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ConfiguracaoFilter>;
};


export type QueryLojasArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryLojasConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<LojasFilter>;
};


export type QueryProdutosArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProdutosConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProdutosFilter>;
};

export type DocumentFilter = {
  configuracao?: InputMaybe<ConfiguracaoFilter>;
  lojas?: InputMaybe<LojasFilter>;
  produtos?: InputMaybe<ProdutosFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Configuracao | Lojas | Produtos | Folder;

export type Configuracao = Node & Document & {
  __typename?: 'Configuracao';
  nomeEmpresa: Scalars['String']['output'];
  slogan?: Maybe<Scalars['String']['output']>;
  telefoneGeral?: Maybe<Scalars['String']['output']>;
  nif?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  rodapeTalao?: Maybe<Scalars['String']['output']>;
  modeloWhatsApp?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ConfiguracaoFilter = {
  nomeEmpresa?: InputMaybe<StringFilter>;
  slogan?: InputMaybe<StringFilter>;
  telefoneGeral?: InputMaybe<StringFilter>;
  nif?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  rodapeTalao?: InputMaybe<StringFilter>;
  modeloWhatsApp?: InputMaybe<StringFilter>;
};

export type ConfiguracaoConnectionEdges = {
  __typename?: 'ConfiguracaoConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Configuracao>;
};

export type ConfiguracaoConnection = Connection & {
  __typename?: 'ConfiguracaoConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ConfiguracaoConnectionEdges>>>;
};

export type Lojas = Node & Document & {
  __typename?: 'Lojas';
  codigo: Scalars['String']['output'];
  nome: Scalars['String']['output'];
  morada: Scalars['String']['output'];
  telefone?: Maybe<Scalars['String']['output']>;
  horario?: Maybe<Scalars['String']['output']>;
  nif?: Maybe<Scalars['String']['output']>;
  foto?: Maybe<Scalars['String']['output']>;
  ativo?: Maybe<Scalars['Boolean']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type LojasFilter = {
  codigo?: InputMaybe<StringFilter>;
  nome?: InputMaybe<StringFilter>;
  morada?: InputMaybe<StringFilter>;
  telefone?: InputMaybe<StringFilter>;
  horario?: InputMaybe<StringFilter>;
  nif?: InputMaybe<StringFilter>;
  foto?: InputMaybe<ImageFilter>;
  ativo?: InputMaybe<BooleanFilter>;
};

export type LojasConnectionEdges = {
  __typename?: 'LojasConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Lojas>;
};

export type LojasConnection = Connection & {
  __typename?: 'LojasConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<LojasConnectionEdges>>>;
};

export type Produtos = Node & Document & {
  __typename?: 'Produtos';
  nome: Scalars['String']['output'];
  categoria: Scalars['String']['output'];
  unidade?: Maybe<Scalars['String']['output']>;
  descricao?: Maybe<Scalars['String']['output']>;
  alergenios?: Maybe<Scalars['String']['output']>;
  foto?: Maybe<Scalars['String']['output']>;
  destaqueMontra?: Maybe<Scalars['Boolean']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ProdutosFilter = {
  nome?: InputMaybe<StringFilter>;
  categoria?: InputMaybe<StringFilter>;
  unidade?: InputMaybe<StringFilter>;
  descricao?: InputMaybe<StringFilter>;
  alergenios?: InputMaybe<StringFilter>;
  foto?: InputMaybe<ImageFilter>;
  destaqueMontra?: InputMaybe<BooleanFilter>;
};

export type ProdutosConnectionEdges = {
  __typename?: 'ProdutosConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Produtos>;
};

export type ProdutosConnection = Connection & {
  __typename?: 'ProdutosConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProdutosConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateConfiguracao: Configuracao;
  createConfiguracao: Configuracao;
  updateLojas: Lojas;
  createLojas: Lojas;
  updateProdutos: Produtos;
  createProdutos: Produtos;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateConfiguracaoArgs = {
  relativePath: Scalars['String']['input'];
  params: ConfiguracaoMutation;
};


export type MutationCreateConfiguracaoArgs = {
  relativePath: Scalars['String']['input'];
  params: ConfiguracaoMutation;
};


export type MutationUpdateLojasArgs = {
  relativePath: Scalars['String']['input'];
  params: LojasMutation;
};


export type MutationCreateLojasArgs = {
  relativePath: Scalars['String']['input'];
  params: LojasMutation;
};


export type MutationUpdateProdutosArgs = {
  relativePath: Scalars['String']['input'];
  params: ProdutosMutation;
};


export type MutationCreateProdutosArgs = {
  relativePath: Scalars['String']['input'];
  params: ProdutosMutation;
};

export type DocumentUpdateMutation = {
  configuracao?: InputMaybe<ConfiguracaoMutation>;
  lojas?: InputMaybe<LojasMutation>;
  produtos?: InputMaybe<ProdutosMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  configuracao?: InputMaybe<ConfiguracaoMutation>;
  lojas?: InputMaybe<LojasMutation>;
  produtos?: InputMaybe<ProdutosMutation>;
};

export type ConfiguracaoMutation = {
  nomeEmpresa?: InputMaybe<Scalars['String']['input']>;
  slogan?: InputMaybe<Scalars['String']['input']>;
  telefoneGeral?: InputMaybe<Scalars['String']['input']>;
  nif?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  rodapeTalao?: InputMaybe<Scalars['String']['input']>;
  modeloWhatsApp?: InputMaybe<Scalars['String']['input']>;
};

export type LojasMutation = {
  codigo?: InputMaybe<Scalars['String']['input']>;
  nome?: InputMaybe<Scalars['String']['input']>;
  morada?: InputMaybe<Scalars['String']['input']>;
  telefone?: InputMaybe<Scalars['String']['input']>;
  horario?: InputMaybe<Scalars['String']['input']>;
  nif?: InputMaybe<Scalars['String']['input']>;
  foto?: InputMaybe<Scalars['String']['input']>;
  ativo?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ProdutosMutation = {
  nome?: InputMaybe<Scalars['String']['input']>;
  categoria?: InputMaybe<Scalars['String']['input']>;
  unidade?: InputMaybe<Scalars['String']['input']>;
  descricao?: InputMaybe<Scalars['String']['input']>;
  alergenios?: InputMaybe<Scalars['String']['input']>;
  foto?: InputMaybe<Scalars['String']['input']>;
  destaqueMontra?: InputMaybe<Scalars['Boolean']['input']>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type ConfiguracaoFilter = {
  nomeEmpresa?: StringFilter | null | undefined;
  slogan?: StringFilter | null | undefined;
  telefoneGeral?: StringFilter | null | undefined;
  nif?: StringFilter | null | undefined;
  email?: StringFilter | null | undefined;
  rodapeTalao?: StringFilter | null | undefined;
  modeloWhatsApp?: StringFilter | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type BooleanFilter = {
  eq?: boolean | null | undefined;
  exists?: boolean | null | undefined;
};

export type LojasFilter = {
  codigo?: StringFilter | null | undefined;
  nome?: StringFilter | null | undefined;
  morada?: StringFilter | null | undefined;
  telefone?: StringFilter | null | undefined;
  horario?: StringFilter | null | undefined;
  nif?: StringFilter | null | undefined;
  foto?: ImageFilter | null | undefined;
  ativo?: BooleanFilter | null | undefined;
};

export type ProdutosFilter = {
  nome?: StringFilter | null | undefined;
  categoria?: StringFilter | null | undefined;
  unidade?: StringFilter | null | undefined;
  descricao?: StringFilter | null | undefined;
  alergenios?: StringFilter | null | undefined;
  foto?: ImageFilter | null | undefined;
  destaqueMontra?: BooleanFilter | null | undefined;
};

export type ConfiguracaoPartsFragment = { __typename: 'Configuracao', nomeEmpresa: string, slogan: string | null, telefoneGeral: string | null, nif: string | null, email: string | null, rodapeTalao: string | null, modeloWhatsApp: string | null };

export type LojasPartsFragment = { __typename: 'Lojas', codigo: string, nome: string, morada: string, telefone: string | null, horario: string | null, nif: string | null, foto: string | null, ativo: boolean | null };

export type ProdutosPartsFragment = { __typename: 'Produtos', nome: string, categoria: string, unidade: string | null, descricao: string | null, alergenios: string | null, foto: string | null, destaqueMontra: boolean | null };

export type ConfiguracaoQueryVariables = Exact<{
  relativePath: string;
}>;


export type ConfiguracaoQuery = { configuracao: { __typename: 'Configuracao', id: string, nomeEmpresa: string, slogan: string | null, telefoneGeral: string | null, nif: string | null, email: string | null, rodapeTalao: string | null, modeloWhatsApp: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ConfiguracaoConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: ConfiguracaoFilter | null | undefined;
}>;


export type ConfiguracaoConnectionQuery = { configuracaoConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Configuracao', id: string, nomeEmpresa: string, slogan: string | null, telefoneGeral: string | null, nif: string | null, email: string | null, rodapeTalao: string | null, modeloWhatsApp: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type LojasQueryVariables = Exact<{
  relativePath: string;
}>;


export type LojasQuery = { lojas: { __typename: 'Lojas', id: string, codigo: string, nome: string, morada: string, telefone: string | null, horario: string | null, nif: string | null, foto: string | null, ativo: boolean | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type LojasConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: LojasFilter | null | undefined;
}>;


export type LojasConnectionQuery = { lojasConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Lojas', id: string, codigo: string, nome: string, morada: string, telefone: string | null, horario: string | null, nif: string | null, foto: string | null, ativo: boolean | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ProdutosQueryVariables = Exact<{
  relativePath: string;
}>;


export type ProdutosQuery = { produtos: { __typename: 'Produtos', id: string, nome: string, categoria: string, unidade: string | null, descricao: string | null, alergenios: string | null, foto: string | null, destaqueMontra: boolean | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ProdutosConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: ProdutosFilter | null | undefined;
}>;


export type ProdutosConnectionQuery = { produtosConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Produtos', id: string, nome: string, categoria: string, unidade: string | null, descricao: string | null, alergenios: string | null, foto: string | null, destaqueMontra: boolean | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const ConfiguracaoPartsFragmentDoc = gql`
    fragment ConfiguracaoParts on Configuracao {
  __typename
  nomeEmpresa
  slogan
  telefoneGeral
  nif
  email
  rodapeTalao
  modeloWhatsApp
}
    `;
export const LojasPartsFragmentDoc = gql`
    fragment LojasParts on Lojas {
  __typename
  codigo
  nome
  morada
  telefone
  horario
  nif
  foto
  ativo
}
    `;
export const ProdutosPartsFragmentDoc = gql`
    fragment ProdutosParts on Produtos {
  __typename
  nome
  categoria
  unidade
  descricao
  alergenios
  foto
  destaqueMontra
}
    `;
export const ConfiguracaoDocument = gql`
    query configuracao($relativePath: String!) {
  configuracao(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ConfiguracaoParts
  }
}
    ${ConfiguracaoPartsFragmentDoc}`;
export const ConfiguracaoConnectionDocument = gql`
    query configuracaoConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ConfiguracaoFilter) {
  configuracaoConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ConfiguracaoParts
      }
    }
  }
}
    ${ConfiguracaoPartsFragmentDoc}`;
export const LojasDocument = gql`
    query lojas($relativePath: String!) {
  lojas(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...LojasParts
  }
}
    ${LojasPartsFragmentDoc}`;
export const LojasConnectionDocument = gql`
    query lojasConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: LojasFilter) {
  lojasConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...LojasParts
      }
    }
  }
}
    ${LojasPartsFragmentDoc}`;
export const ProdutosDocument = gql`
    query produtos($relativePath: String!) {
  produtos(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProdutosParts
  }
}
    ${ProdutosPartsFragmentDoc}`;
export const ProdutosConnectionDocument = gql`
    query produtosConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProdutosFilter) {
  produtosConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProdutosParts
      }
    }
  }
}
    ${ProdutosPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      configuracao(variables: ConfiguracaoQueryVariables, options?: C): Promise<{data: ConfiguracaoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfiguracaoQueryVariables, query: string}> {
        return requester<{data: ConfiguracaoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfiguracaoQueryVariables, query: string}, ConfiguracaoQueryVariables>(ConfiguracaoDocument, variables, options);
      },
    configuracaoConnection(variables?: ConfiguracaoConnectionQueryVariables, options?: C): Promise<{data: ConfiguracaoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfiguracaoConnectionQueryVariables, query: string}> {
        return requester<{data: ConfiguracaoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConfiguracaoConnectionQueryVariables, query: string}, ConfiguracaoConnectionQueryVariables>(ConfiguracaoConnectionDocument, variables, options);
      },
    lojas(variables: LojasQueryVariables, options?: C): Promise<{data: LojasQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LojasQueryVariables, query: string}> {
        return requester<{data: LojasQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LojasQueryVariables, query: string}, LojasQueryVariables>(LojasDocument, variables, options);
      },
    lojasConnection(variables?: LojasConnectionQueryVariables, options?: C): Promise<{data: LojasConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LojasConnectionQueryVariables, query: string}> {
        return requester<{data: LojasConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: LojasConnectionQueryVariables, query: string}, LojasConnectionQueryVariables>(LojasConnectionDocument, variables, options);
      },
    produtos(variables: ProdutosQueryVariables, options?: C): Promise<{data: ProdutosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProdutosQueryVariables, query: string}> {
        return requester<{data: ProdutosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProdutosQueryVariables, query: string}, ProdutosQueryVariables>(ProdutosDocument, variables, options);
      },
    produtosConnection(variables?: ProdutosConnectionQueryVariables, options?: C): Promise<{data: ProdutosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProdutosConnectionQueryVariables, query: string}> {
        return requester<{data: ProdutosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProdutosConnectionQueryVariables, query: string}, ProdutosConnectionQueryVariables>(ProdutosConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  